# Generated by Django 3.1 on 2021-12-25 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0004_auto_20211221_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Katalog'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Aloqa'},
        ),
        migrations.AlterModelOptions(
            name='registertable',
            options={'verbose_name_plural': 'Talabalar'},
        ),
        migrations.CreateModel(
            name='Add_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('product_img', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
